spring:
datasource:
type: com.alibaba.druid.pool.DruidDataSource
username: root
password: 613128
url: jdbc:mysql://localhost:3306/example?serverTimeZone=Asia/Shanghai

mvc:
pathmatch:
matching-strategy: ant-path-matcher