# 应用服务 WEB 访问端口
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
file:
   upload:
     url:
spring:
  servlet:
      multipart:
        enabled: true
        max-file-size: 20MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 2890844749@qq.com #这里填你的邮箱
    password: grfhgacoszntdhed #这里填你的授权码
    default-encoding: UTF-8

  mvc:
    path match:
      matching-strategy: ant-path-matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 20030105
    url: jdbc:mysql://localhost:3306/mybd?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8

