spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306?serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
