spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1128yyqx
    url: jdbc:mysql://localhost:3306/example?serverTimeZone=Asia/Shanghai
