spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 18819903925s
    url: jdbc:mysql://localhost:3306/example?serverTimeZone=Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
