spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/example?serverTimeZone=Asia/Shanghai
  mvc:
  pathmatch:
  matching-strategy: ant-path-matcher
  security:
    user:
      name: admin
      password: 123456
  mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
  server:
    port: 8081
  mail:
    host: smtp.qq.com
    port: 587
    username: <EMAIL>
    password: 123456
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
file:
  upload:
    url: D:/downloads/upload