spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ljj20031101
    url: jdbc:mysql://localhost:3306/example1?serverTimeZone=Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher