spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306?serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

  security:
    user:
    name: admin
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.qq.com
    port: 587
    username: 2425683342@qq.com  #这里填你的邮箱
    password: cuhaeftjlcdnebcf #这里填你的授权码
    default-encoding: UTF-8

# 文件上传目录

  # 设置最大的文件大小，不超过20MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

file:
  upload:
    url: C:\Users\linwei\Desktop\test