spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ds123456A
    url: jdbc:mysql://localhost:3306/example?serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8
  security:
    user:
      name: admin
      password: 123456
  mvc:
    path match:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml