spring:
  mvc:
    path match:
      matching-strategy: ant-path-matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 17883577980lqs
    url: jdbc:mysql://localhost:3306/mydb?serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8

