spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/javaweb?serverTimeZone=Asia/Shanghai
  mvc:
    path match:
      matching-strategy: ant-path-matcher
  security:
    user:
      name: admin
      password: 123456
  mail:
    host: smtp.qq.com
    port: 587
    username: 2176044349@qq.com #这里填你的邮箱
    password: daycbygsrmuwdihc #这里填你的授权码
    default-encoding: UTF-8
# 文件上传目录
file:
  upload:
    url: C:\Users\21760\Desktop\a
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

