spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/javaweb?serverTimeZone=Asia/Shanghai
  mvc:
    path match:
      matching-strategy: ant-path-matcher
  security:
    user:
      name: admin
      password: 123456
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
