spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xia123456
    url: jdbc:mysql://localhost:3306/mydb?serverTimeZone=Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: 8080


